spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/taiso
    username: ssafy
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show-sql: true
      logging:
        level:
          # 얘는 로그를 통해서 보여줌
          org.hibernate.SQL: debug
          org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
