server:
  port: 3000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://j10d212.p.ssafy.io:3306/TAISO
    username: localTaiso
    password: taiso1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

      logging:
        level:
          # 얘는 로그를 통해서 보여줌
          org.hibernate.SQL: debug
          org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
          org.springframework.security.web: trace

springdoc: #swagger
  packages-to-scan: com.d212.taiso
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /taiso-ui.html            # Swagger UI 경로 => localhost:8000/taiso-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true